vich_uploader:
    db_driver: orm

    mappings:
        article:
            uri_prefix: /article/image
            upload_destination: '%kernel.project_dir%/var/article'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: false
            delete_on_remove: false
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
